[workspace]
authors = ["Jaeho Cho <jaeho2025@gmail.com>"]
channels = ["robostack-kilted", "conda-forge"]
name = "budgie_bot"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-kilted-ros-workspace = "*"
